export const COPYRIGHT_HOLDERS = [
  { company: "Nonghyup Bank", name: "Jang Seonghoon" },
  { company: "Bank of Korea", name: "Do Jiyun" }
];

export const COPYRIGHT_LINE = `© ${new Date().getFullYear()} Nonghyup Bank Jang Seonghoon and Bank of Korea Do Jiyun. All rights reserved.`;

export const COPYRIGHT_NOTICE =
  "This material consists of summaries and analytical outputs generated by a personal local economy news dashboard and is provided for internal reference and learning purposes only. Copyrights in original articles and third-party content remain with their respective publishers and rights holders. Unauthorized distribution, commercial use, or use as a substitute for the original source content is prohibited.";
